### PR TITLE
Php8 Compatability 

### PR DESCRIPTION
**Pull request by robbamos**
Follow up for php8 compatability from GH-74

### CODE REVIEW

**Comment by joeworkman** [comment]
@colinodell Any chance of looking at this one for merge?

**Comment by jadeops** [comment]
It's been more than 5 months https://github.com/thephpleague/color-extractor/pull/74 Please merge.

**Review by colinodell — APPROVED** [review]

**Comment by colinodell** [comment]
[v0.4.0](https://github.com/thephpleague/color-extractor/releases/tag/0.4.0) has been released with PHP 8 compatibility.  Thanks for the PR!

**Comment by jadeops** [comment]
Thank you! but it's not showing up on packagist/composer. https://packagist.org/packages/league/color-extractor

Screenshot_2022-09-24_22-45-19

**Comment by colinodell** [comment]
Ah, let me try to get access to publish it there.

**Comment by colinodell** [comment]
Fixed! https://packagist.org/packages/league/color-extractor#0.4.0

**Comment by jadeops** [comment]
Thank you very much!

**Pull request merged**
