### PR TITLE
Basic PHP 8 support

### PR DESCRIPTION
**Pull request by sandrolain**
Added usage verification of GD image source as GdImage class instance. Ref issue #64

### CODE REVIEW

**Comment by carestad** [comment]
@MatTheCat could you perhaps review this at your earliest convenience? :smiley:

**Comment by MatTheCat** [comment]
Hey it's been a long time since I came on this repository..!

I believe `instanceof` does not trigger any error if you test against an undefined class so it would make the condition simpler. 🤔

**Comment by Mihairu35** [comment]
Hello!
I use simple code for extracting colors from GD resource:

```
$palette = Palette::fromGD($image);
$colors = $palette->getMostUsedColors($count);
```

But php 8 throws exception - Image must be a gd resource. 
I've add check for instanceof \GdImage, if current php version is 8.0 or higher in my pull request - #67

```
if (PHP_VERSION_ID >= 80000) {
            if (!(is_resource($image) || $image instanceof \GdImage)) {
                throw new \InvalidArgumentException('Image must be a gd resource');
            }
        } else {
            if (!is_resource($image) || get_resource_type($image) != 'gd') {
                throw new \InvalidArgumentException('Image must be a gd resource');
            }
        }
```

This code helped me. I tested on php 7.4, this also works fine. I think this might be useful.)

**Comment by MatTheCat** [comment]
Couldn't you just write

```php
if (!$image instanceof \GDImage && (!is_resource($image) || 'gd' !== get_resource_type($image))) {
    throw... 
}
```
?

**Comment by Mihairu35** [comment]
Yes, it works, thank you! It's much simplier solution.
```
if (!$image instanceof \GDImage && (!is_resource($image) || 'gd' !== get_resource_type($image))) 
                throw new \InvalidArgumentException('Image must be a gd resource');
            }
```

Can I add this code into my pull?

**Comment by MatTheCat** [comment]
Yes go ahead 🙂
Maybe the error message could be changed based on PHP version though?

**Comment by Mihairu35** [comment]
Maybe, but now it's working fine, thanks))
I made pull request #68

**Comment by colinodell** [comment]
Closing this in favor of #74 since that also comes with working tests to verify the fix.  Appreciate the help here, though!

**Pull request closed without merging**
