### PR TITLE
0.2.0

### PR DESCRIPTION
**Pull request by MatTheCat**
Considering #17 I think it would be interesting to allow the `Image` class to offer any color-related functionality.
For now we just have the implicit `extract` method which prevents consistency, it certainly means there will be some BC.

Any idea of how to do that properly?

### CODE REVIEW

**Comment by philsturgeon** [comment]
Copied over from the commit:

> I won't drop PHP 5.3 if it's just for short array syntax ^^

Oh I know, I wrote a whole blog post about how daft it was to force version updates based entirely for something as pointless as short array syntax, but the point was more that you should probably be moving away from supporting EOL versions of PHP. 

The rule many packages here use is each major version supports the last 3 versions of PHP, so long as they're all still supported by PHP themselves. That means the previous version is always available to others who need it, and the new stuff can move on with more features.

Noticing the long arrays made me notice you were still supporting PHP 5.3 more than anything else. There's most likely a lot of improvements you could make going 5.5+.

**Comment by MatTheCat** [comment]
I can't think on any improvement from last PHP versions I could use. Apart from short array syntax.
It was my point for still supporting PHP 5.3 but it's not really a problem for me to drop it.

**Comment by MatTheCat** [comment]
I think I can merge this now, maybe under tag 0.2.0-beta?

**Comment by toin0u** [comment]
:+1: :fireworks:

**Pull request merged**
